### ISSUE TITLE
Doesn't work with floated images

### ISSUE THREAD

**Issue by edge0703** [ctrl-freaks/freezeframe.js#34] opened 2017-03-24 07:23 UTC
Everything works fine when I use freezeframe with non-floated images, but the moment I use `float: left` or `float: right` (on the parent element) I can't click the image anymore. Any suggestions?

**Comment by chrisantonellis** [comment] 2017-12-21 02:06
i'll try to reproduce and report back, thanks!

**Comment by chrisantonellis** [comment] 2018-05-21 20:46
unable to reproduce, closing this for now, you can open another issue if you want to provide a codepen that reproduces the issue. Thanks!

**Closed by chrisantonellis** 2018-05-21 20:46 UTC
Labels: bug
